### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'Thread-1'

### ISSUE THREAD

**Issue by p-enel** [realgud/realgud-ipdb#6]
This package looks awesome, I installed it with elpa (I'm using spacemacs).
realgud:pdb works just fine, ipdb by itself works fine as well, but I have a repeating error/traceback when I start realgud:ipdb

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/pierre/Apps/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/pierre/Apps/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pierre/Apps/anaconda3/lib/python3.7/site-packages/IPython/terminal/debugger.py", line 122, in in_thread
    line = self.pt_app.prompt()
  File "/home/pierre/Apps/anaconda3/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1011, in prompt
    return get_event_loop().run_until_complete(self._dumb_prompt(self.message))
  File "/home/pierre/Apps/anaconda3/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-1'.

```
This error repeats indefinitely, incrementing the thread number at each iteration. It fills up the screen so fast that you get to millions of characters in the buffer in a matter of seconds.

To reproduce this:
- install realgud and realgud-ipdb (in spacemacs these packages are inserted in dotspacemacs-additional-packages)
- open a python script
- realgud is already loaded, but I need to load realgud-ipdb: M-x load-library  then realgud-ipdb
- M-x realgud:ipdb
- I use the default command: ipdb script.py
- I get the error above

I checked, all the package dependencies specified in the realgud tutorial are installed.
Thanks for your help and that cool package!

**Comment by rocky** [comment]
Thanks for the kid words. Open-source software is only as good as people who have the time and are willing to work on it

This project and realgud in general has always been lacking in people helping out. 

Personally, I don't use ipdb - I've written and use my own debuggers. (That said, I have no doubt the problem really is in or related to something in realgud core).  

If you are interested in investigating and fixing, please do so. I can help with questions you have related to how the code works. Otherwise, I guess this will serve to note there is a problem and maybe someone in the future will be interested in fixing.

**Comment by it-is-wednesday** [comment]
Can confirm it happens to me as well. I'm eager to use this package, so I'll allocate some quarantine time for it ;)
